#!/bin/bash
# NOTE: put key with limited access (e.g. bucket path only) in passwd-s3fs 
s3fs <BUCKET>:/watchlists /mnt/watchlists \
    -o passwd_file=/etc/passwd-s3fs \
    -o endpoint=eu-north-1 \
    -o url=https://s3.eu-north-1.amazonaws.com \
    -o use_path_request_style \
    -o allow_other \
    -o uid=1000 \
    -o gid=1000 \
    -o mp_umask=022 \
    -o compat_dir
